import type { AppPreferences } from './types'

/** 默认偏好（对齐 qB 出厂值，设置页加载失败/未加载时的兜底表单值） */
export const DEFAULT_PREFERENCES: AppPreferences = {
  /* 行为 */
  locale: 'zh_CN',
  add_stopped_enabled: false,
  confirm_torrent_deletion: true,
  confirm_torrent_recheck: true,
  auto_delete_mode: 0,
  preallocate_all: false,
  incomplete_files_ext: false,
  use_category_paths_in_manual_mode: true,
  torrent_changed_tmm_enabled: true,
  save_path_changed_tmm_enabled: true,
  category_changed_tmm_enabled: true,
  autorun_enabled: false,
  autorun_on_torrent_added_enabled: false,
  autorun_program: '',

  /* 下载 */
  save_path: '/downloads',
  temp_path_enabled: false,
  temp_path: '/downloads/incomplete',
  export_dir: '',
  export_dir_fin: '',
  scan_dirs: '',
  mail_notification_enabled: false,
  mail_notification_email: '',
  mail_notification_smtp: 'smtp://smtp.example.com:587',
  mail_notification_ssl_enabled: false,
  mail_notification_auth_enabled: false,
  mail_notification_username: '',
  mail_notification_password: '',

  /* 连接 */
  listen_port: 6881,
  upnp: true,
  random_port: false,
  max_connec: 500,
  max_connec_per_torrent: 100,
  max_uploads: 40,
  max_uploads_per_torrent: 8,
  proxy_type: -1,
  proxy_ip: '0.0.0.0',
  proxy_port: 8080,
  proxy_peer_connections: false,
  proxy_auth_enabled: false,
  proxy_username: '',
  proxy_password: '',
  proxy_torrents_only: false,

  /* 速度 */
  dl_limit: 0,
  up_limit: 0,
  alt_dl_limit: 10240,
  alt_up_limit: 10240,
  scheduler_enabled: false,
  schedule_from_hour: 8,
  schedule_from_min: 0,
  schedule_to_hour: 20,
  schedule_to_min: 0,
  scheduler_days: 0,
  limit_utp_rate: false,
  limit_tcp_overhead: false,
  limit_lan_peers: false,

  /* BitTorrent */
  encryption: 0,
  anonymous_mode: false,
  bittorrent_protocol: 0,
  max_active_downloads: 5,
  max_active_torrents: 8,
  max_active_uploads: 4,
  queueing_enabled: true,
  dont_count_slow_torrents: true,
  slow_torrent_dl_rate_threshold: 2,
  slow_torrent_ul_rate_threshold: 2,
  slow_torrent_inactive_timer: 60,
  max_ratio_enabled: false,
  max_ratio: 1.5,
  max_ratio_act: 0,
  max_seeding_time_enabled: false,
  max_seeding_time: 1440,
  dht: true,
  pex: true,
  lsd: true,
  add_trackers_enabled: false,
  add_trackers: '',

  /* Web UI */
  web_ui_domain_list: '*',
  web_ui_address: '*',
  web_ui_port: 8080,
  web_ui_upnp: false,
  web_ui_username: 'admin',
  web_ui_password: '',
  web_ui_csrf_protection_enabled: true,
  web_ui_clickjacking_protection_enabled: true,
  web_ui_secure_cookie_enabled: true,
  web_ui_host_header_validation_enabled: true,
  web_ui_https_enabled: false,
  web_ui_https_cert_path: '',
  web_ui_https_key_path: '',
  web_ui_max_auth_fail_count: 5,
  web_ui_ban_duration: 3600,
  web_ui_session_timeout: 36000,
  alternative_webui_enabled: false,
  alternative_webui_path: '',
  web_ui_use_custom_http_headers_enabled: false,
  web_ui_custom_http_headers: '',
  bypass_local_auth: true,
  bypass_auth_subnet_whitelist_enabled: false,
  bypass_auth_subnet_whitelist: '',

  /* RSS */
  rss_refresh_interval: 30,
  rss_max_articles_per_feed: 100,
  rss_processing_enabled: false,
  rss_auto_downloading_enabled: false,

  /* 高级 */
  async_io_threads: 10,
  hashing_threads: 2,
  socket_backlog: 30,
  outgoing_ports_min: 0,
  outgoing_ports_max: 0,
  upnp_lease_duration: 0,
  utp_tcp_mixed_mode: 0,
  send_buffer_watermark: 512,
  send_buffer_low_watermark: 10,
  send_buffer_watermark_factor: 150,
  disk_cache_size: -1,
  disk_queue_size: 1048576,
  disk_io_read_mode: 0,
  disk_io_write_mode: 0,
  upload_choking_algorithm: 1,
  upload_slots_behavior: 0,
  announce_ip: '',
  max_concurrent_http_announces: 50,
  stop_tracker_timeout: 2,
  enable_embedded_tracker: false,
  embedded_tracker_port: 9000,
  embedded_tracker_port_forwarding: false,
  enable_multi_connections_from_same_ip: false,
  validate_https_tracker_certificate: false,
  ssrf_mitigation: true,
  recheck_torrents_on_completion: false,
  refresh_interval: 1500,
  resolve_peer_countries: true,
  reannounce_when_address_changed: false,
  enable_os_cache: true,
}
